config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :users, only: [] do
    resources :experiences, only: [:new, :create, :index]
  end

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :user

  validates :company_name,
    presence: true
  validates :company_city,
    presence: true
  validates :company_state,
    presence: true
  validates :start_date,
    presence: true
  #do not validate end date because a user may currently be working there
  validates :title,
    presence: true

  validate :end_date_with_current

  def end_date_with_current
    if current && end_date
      errors.add(
        :end_date,
        "There should not be an end date if this is a current experience"
      )
    end
  end

  def location
    "#{company_city}, #{company_state}"
  end

  ######## Allow users to format the date however they wish ########
  def flexible_date
    dates = Hash.new({})
    dates[:start_date] = {
      month: self.start_date.strftime("%B"),
      year: self.start_date.year
    }

    if self.end_date
      dates[:end_date] = {
        month: self.end_date.strftime("%B"),
        year: self.end_date.year
      }
    end

    dates
  end

  def formatted_date
    formatted_dates = {}
    flexible_dates = flexible_date
    date_periods = flexible_dates.keys.map { |period| period }

    date_periods.each do |period|
      date_period = flexible_dates[period]
      formatted_dates[period] = "#{date_period[:month]} #{date_period[:year]}"
    end

    formatted_dates
  end

  def self.us_states
  [
    ['Alabama', 'AL'],
    ['Alaska', 'AK'],
    ['Arizona', 'AZ'],
    ['Arkansas', 'AR'],
    ['California', 'CA'],
    ['Colorado', 'CO'],
    ['Connecticut', 'CT'],
    ['Delaware', 'DE'],
    ['District of Columbia', 'DC'],
    ['Florida', 'FL'],
    ['Georgia', 'GA'],
    ['Hawaii', 'HI'],
    ['Idaho', 'ID'],
    ['Illinois', 'IL'],
    ['Indiana', 'IN'],
    ['Iowa', 'IA'],
    ['Kansas', 'KS'],
    ['Kentucky', 'KY'],
    ['Louisiana', 'LA'],
    ['Maine', 'ME'],
    ['Maryland', 'MD'],
    ['Massachusetts', 'MA'],
    ['Michigan', 'MI'],
    ['Minnesota', 'MN'],
    ['Mississippi', 'MS'],
    ['Missouri', 'MO'],
    ['Montana', 'MT'],
    ['Nebraska', 'NE'],
    ['Nevada', 'NV'],
    ['New Hampshire', 'NH'],
    ['New Jersey', 'NJ'],
    ['New Mexico', 'NM'],
    ['New York', 'NY'],
    ['North Carolina', 'NC'],
    ['North Dakota', 'ND'],
    ['Ohio', 'OH'],
    ['Oklahoma', 'OK'],
    ['Oregon', 'OR'],
    ['Pennsylvania', 'PA'],
    ['Puerto Rico', 'PR'],
    ['Rhode Island', 'RI'],
    ['South Carolina', 'SC'],
    ['South Dakota', 'SD'],
    ['Tennessee', 'TN'],
    ['Texas', 'TX'],
    ['Utah', 'UT'],
    ['Vermont', 'VT'],
    ['Virginia', 'VA'],
    ['Washington', 'WA'],
    ['West Virginia', 'WV'],
    ['Wisconsin', 'WI'],
    ['Wyoming', 'WY']
  ]
end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :experiences
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_filter :authenticate_user!

  def new
    @user = current_user
    @experience = @user.experiences.new
  end

  def create
    @user = current_user
    @experience = @user.experiences.new(experience_params)

    if @experience.save
      flash[:notice] = "Experience successfully added"
      redirect_to user_experiences_path(@user)
    else
      flash[:errors] = @experience.errors.full_messages.join(', ')
      render :new
    end
  end

  def index
    @user = current_user
    @experiences = @user.experiences.all
  end

  private

  def experience_params
    params.require(:experience).permit(
      :user, :company_name, :company_city, :company_state, :start_date,
      :end_date, :title, :current
    )
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/views/experiences/index.html.erb
<section id="experiences-list">
  <header>
    <h3 class="text-center">Experience</h3>
  </header>

  <div class="flex-row full-width text-center">
    <h5 class="experience-title">Title</h5>

    <span class="experience-name">Company Name</span>
    <span class="experience-location">Company Position</span>
    <span class="experience-start">Start Date</span>
    <span class="experience-end">End Date</span>
  </div>

  <% @experiences.each do |experience| %>
    <div class="flex-row full-width text-center">
      <h5 class="experience-title"><%= experience.title %></h5>

      <span class="experience-name">
        <%= experience.company_name %>
      </span>
      <span class="experience-location">
        <%= "#{experience.company_city}, #{experience.company_state}" %>
      </span>
      <span class="experience-start">
        <%= experience.formatted_date[:start_date] %>
      </span>
      <span class="experience-end">
        <%= experience.current ? 'Current' : experience.formatted_date[:end_date] %>
      </span>
    </div>
  <% end %>
</section>

app/views/experiences/new.html.erb
<section class="new-form">
  <header>
    <h3 class="text-center">Add New Experience</h3>

    <%= form_for([@user, @experience]) do |f| %>
      <div class="row">
        <span>
          <%= f.label :title %>
          <%= f.text_field :title %>
        </span>
      </div>

      <div class="row">
        <span>
          <%= f.label :company_name %>
          <%= f.text_field :company_name %>
        </span>
      </div>

      <div class="row">
        <%= f.label :company_city %>
        <%= f.text_field :company_city %>
      </div>

      <div class="row">
        <%= f.label :company_state %>
        <%= f.select :company_state do %>
          <% Experience.us_states.each do |state| %>
            <%= content_tag :option, state.last %>
          <% end %>
        <% end %>
      </div>

      <div class="row">
        <%= f.label :start_date, 'Start date' %>
        <%= f.date_select :start_date,
          order: [:month, :year],
          start_date: '1980',
          end_date: '2015',
          start_year: Date.today.year - 30,
          end_year: Date.today.year
        %>
      </div>

      <div class="row">
        <div id="current_experience-container">
          <%= f.label :current %>
          <%= f.check_box :current, checked: true %>
        </div>
      </div>

      <div class="row">
        <div id="end-date-container" class="hidden">
          <%= f.label :end_date, 'End date' %>
          <%= f.date_select :end_date,
            order: [:month, :year],
            start_date: '1980',
            end_date: '2015',
            start_year: Date.today.year - 30,
            end_year: Date.today.year,
            include_blank: true,
            default: nil
          %>
        </div>
      </div>

      <div class="row text-center">
        <%= f.submit "Submit", class: "button" %>
      </div>
    <% end %>
  </header>
</section>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Showcase</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Damion" />
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Showcase</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><a href="#" data-dropdown="hover1" data-options="is_hover:true">Experience</a></li>
          <ul id="hover1" class="f-dropdown full-width" data-dropdown-content>
            <li class="full-width text-center"><%= link_to 'Add an Experience', new_user_experience_path(current_user) %></li>
            <li class="full-width text-center"><%= link_to 'View all Experiences',user_experiences_path(current_user) %></li>
          </ul>

          <li><a href="#" data-dropdown="hover2" data-options="is_hover:true"><%= current_user.email %></a></li>
          <ul id="hover2" class="f-dropdown full-width" data-dropdown-content>
            <li class="full-width text-center"><a href="#">This is a link</a></li>
            <li class="full-width text-center"><a href="#">This is another</a></li>
            <li class="full-width text-center"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>